# 예외 처리 하기

- 예외란 처리하지 못한 에러를 말한다.
- 노드는 메인 스레드는 하나 뿐이므로 별다른 처리없이 에러가 발생하면 프로세스가 멈춘다.
- 그러므로 노드로 서버를 운영함에 있어서 에러를 처리하는 것은 매우 중요하다.

## try/catch 문

- 에러가 발생할 것으로 예상되는 부분을 try/catch문으로 감싼다.

```javascript error1.js

setInterval(()=>{
    console.log('시작');
    try {
        throw new Error("서버가 고장남");
    } catch(err){
        console.error(err);
    }
}, 1000);
```

- throw new Error("서버가 고장남"); 로 인해 에러가 발생하지만 setInterval 문은 계속 동작한다.
- 에러를 throw 하는 경우 반드시 try/catch 문으로 throw한 에러를 잡아야 한다.
- 그렇지 않으면 노드 프로세스가 멈춘다.

## 노드 내장 모듈의 에러

```javascript error2.js

const fs = require('fs');

setInterval(()=>{
    fs.unlink('./abc.js', (err)=>{
        if(err){
            console.error(err);
        }
    })
}, 1000);
```

- 존재하지 않는 파일을 삭제하라고 하여 에러가 발생한다.
- 하지만 노드 내장 모듈의 에러는 실행 중인 프로세스를 멈추지 않는다.

## 프로미스의 에러

- 노드 16 버전부터 프로미스의 에러는 반드시 catch 해야 한다. 그렇지 않으면 노드 프로세스가 종료된다.

```javascript error2.js

const fs = require('fs');

setInterval(()=>{
    fs.unlink('./abc.js').catch(console.error);
}, 1000);
```

## uncaugthException

```javascript error4.js

process.on('uncaugthException', (err)=>{
    console.error('예기치 못한 에러', err)
})

setInterval(()=>{
    throw new Error('서버 고장');    
}, 1000);

setTimeout(()=>{
    console.log("실행");
});

```

- process 객체에 uncaugthException 이벤트리스너를 달지 않았다면 setTimeout은 실행되지 않는다.
- 프로세스가 멈추기 때문이다.
- 노드 공식문서에서는 uncaugthException 이벤트 리스너는 최후의 수단으로 사용할 것을 명시하고 있다.
- uncaugthException 이벤트 후에 다음 코드의 동작을 보증하지 않기 때문이다.
- 그러므로 에러 내용을 기록한 후 process.exit()로 프로세스를 종료하는 것이 좋다.

## 자주 발생하는 에러들